// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-CeV5poh5Ag_mZUr3hFfPwqSgwvpBo4g',
    appId: '1:818011659459:web:8f94473dd0a103ce2d5676',
    messagingSenderId: '818011659459',
    projectId: 'my-vpp-91fcf',
    authDomain: 'my-vpp-91fcf.firebaseapp.com',
    storageBucket: 'my-vpp-91fcf.appspot.com',
    measurementId: 'G-7NKD0TJP1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChW_uYHWkJF_MsW_k85w9CxI3kJbPHhEg',
    appId: '1:818011659459:android:edf263d0275551932d5676',
    messagingSenderId: '818011659459',
    projectId: 'my-vpp-91fcf',
    storageBucket: 'my-vpp-91fcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhKmxBQpqFUbC6koeG4fUBnMccgJMsZgM',
    appId: '1:818011659459:ios:3295099e9ac00dfb2d5676',
    messagingSenderId: '818011659459',
    projectId: 'my-vpp-91fcf',
    storageBucket: 'my-vpp-91fcf.appspot.com',
    iosBundleId: 'com.example.myVpp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhKmxBQpqFUbC6koeG4fUBnMccgJMsZgM',
    appId: '1:818011659459:ios:3295099e9ac00dfb2d5676',
    messagingSenderId: '818011659459',
    projectId: 'my-vpp-91fcf',
    storageBucket: 'my-vpp-91fcf.appspot.com',
    iosBundleId: 'com.example.myVpp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-CeV5poh5Ag_mZUr3hFfPwqSgwvpBo4g',
    appId: '1:818011659459:web:0f3015c7d2188ba22d5676',
    messagingSenderId: '818011659459',
    projectId: 'my-vpp-91fcf',
    authDomain: 'my-vpp-91fcf.firebaseapp.com',
    storageBucket: 'my-vpp-91fcf.appspot.com',
    measurementId: 'G-THSXQPZQB2',
  );
}
